# Generated by Django 5.1.6 on 2025-03-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0003_alter_users_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landslideId', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('upazila', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=8)),
                ('historicalInfo', models.TextField()),
                ('remedialMeasures', models.TextField()),
                ('areaOfDisplacedMass', models.CharField(max_length=20)),
                ('NumberOfHouseHolds', models.CharField(max_length=10)),
                ('IncomeLevel', models.CharField(max_length=100)),
                ('injured', models.CharField(max_length=10)),
                ('displaced', models.CharField(max_length=10)),
                ('deaths', models.CharField(max_length=10)),
                ('landslideSettings', models.TextField()),
                ('classificationOfLandSlide', models.CharField(max_length=100)),
                ('meterialType', models.CharField(max_length=100)),
                ('causeOfLandSlide', models.CharField(max_length=100)),
                ('failureType', models.CharField(max_length=100)),
                ('distributionStyle', models.CharField(max_length=100)),
                ('stateOfLandSlide', models.CharField(max_length=100)),
                ('landCoverType', models.CharField(max_length=100)),
                ('landUsedType', models.CharField(max_length=100)),
                ('slopeAngle', models.CharField(max_length=10)),
                ('rainfallData', models.CharField(max_length=20)),
                ('waterTableLevel', models.CharField(max_length=20)),
                ('soilMoistureContent', models.CharField(max_length=20)),
                ('impactOnInfrasturcture', models.TextField()),
                ('damageOfRoads', models.TextField()),
                ('damageToBuildings', models.TextField()),
                ('damageToCriticalnfrastructure', models.TextField()),
                ('damageToUtilities', models.TextField()),
                ('damageToBridge', models.TextField()),
                ('damInfrastructureImpact', models.TextField()),
                ('soilImpact', models.TextField()),
                ('vegetationCoverImpact', models.TextField()),
                ('waterwayImpact', models.TextField()),
                ('economicImpact', models.TextField()),
                ('distanceFromLocation1', models.CharField(max_length=20)),
                ('distanceFromLocation2', models.CharField(max_length=20)),
            ],
        ),
    ]
