# Generated by Django 5.1.6 on 2025-03-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0005_reports_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='imagePath',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
